### ISSUE TITLE
Here is a windows build.  I had to change abs() to fabs() in Tension.cpp

### ISSUE THREAD

**Issue by jeremywen** [naus3a/NauModular#1]
[NauModular.zip](https://github.com/naus3a/NauModular/files/1502305/NauModular.zip)

**Comment by naus3a** [comment]
wow, you were fast: I don't think the repo has been online for a full hour :D

**Comment by jeremywen** [comment]
😄  Are you in the VCV Rack facebook group?  I posted it there https://www.facebook.com/groups/vcvrack/permalink/138062930187193/

**Comment by naus3a** [comment]
yes, I'm there too: my name's enrico viola.
I'm a bit late to the plugin party because, you know, *real work* :P, but really wanted poke my hands into it.

**Comment by jeremywen** [comment]
pfft work....

**Comment by naus3a** [comment]
I know, right?

**Comment by naus3a** [comment]
(fixed the fabs)

**Comment by jeremywen** [comment]
guess you don't need that pull request I made 😄

**Comment by naus3a** [comment]
oh, sorry did not see it... it's already friday night here, brain works on limited resources :)
