### ISSUE TITLE
Use ARCH_* for architecture detection

### ISSUE THREAD

**Issue by AndrewBelt** [naus3a/NauModular#11]
https://github.com/naus3a/NauModular/blob/c7680cda91e7acd6f41301ea9bd79d950845d8a3/src/NauModular.hpp#L3

The Rack way of doing the above is simply
```cpp
#ifdef ARCH_LIN
...
#ifdef ARCH_MAC
...
#ifdef ARCH_WIN
```
because the Makefile system passes these defines as flags to the compiler.

**Comment by naus3a** [comment]
ok!
