### ISSUE TITLE
VERSION update in Makefile

### ISSUE THREAD

**Issue by cschol** [naus3a/NauModular#16]
The VERSION needs to be updated in the Makefile to `0.6.0`, no `dev` suffix. Thank you!

**Comment by naus3a** [comment]
ok, thanks: in the middle of a relocation, so I paused VCV development for a bit. 
the first lazy evening I have, I'm going to get confident with 6.0 :)

**Comment by cschol** [comment]
Thank you. I will provide a PR for this since the release of Rack `0.6` is coming up fast. You'll just need to accept it on Github. That should get this solved pretty easily. PR #17.

**Comment by naus3a** [comment]
Thanks, did it!
