### ISSUE TITLE
Perlin: hitting float limit causes constant output

### ISSUE THREAD

**Issue by cschol** [naus3a/NauModular#19]
After letting the `Perlin` module run for a while the `curTime` variable (a `float`) if "full" hitting the `float` limit and adding `deltaTime` to it does not have any effect anymore, hence producing a constant output.

**Comment by naus3a** [comment]
good spotting :)
thx

**Comment by naus3a** [comment]
I made a quick patch (resetting the variable), but at some point I'll go back to this and figure out the better way to do it.

Calling it close *for now* ;)

**Comment by cschol** [comment]
Thank you. If you update the Makefile to version 0.6.1, I'll pull the new version in the Plugin Manager.

**Comment by naus3a** [comment]
checking the new plugin page and updating in the next days :)

**Comment by naus3a** [comment]
it was a 1 liner: did it!
