### ISSUE TITLE
[bug] Perlin: output mutes after a while.

### ISSUE THREAD

**Issue by phdsg** [naus3a/NauModular#3]
OS: win
Rack: dev
Plugins: dev

somehow the module just goes mute after a while and i can't turn it back on with any of the controls.
also tried the menu options *initialize* and *randomize*.
i have to delete the module and load a fresh instance.

great module ideas btw, thx so much.

**Comment by naus3a** [comment]
Hey, glad you like it :)
I did not test on win, but it could be way I increment the noise position: I'll add safety net around it.

**Comment by MarcBoule** [comment]
I'd like to echo @phdsg 's comment, the same happens to me after a short while. Perlin goes mute, then when I play with the speed button, I can get it back but it doesn't behave the same way afterwards (hard to describe, but it becomes broken). Hope you can figure this out, it's a neat module when speed is relatively low (we can hear a pattern in the sound when speed is high though).

**Comment by naus3a** [comment]
It probably has something to do with range/progression of values I feed: I already noticed that the lowest values I allowed were too low.
It's the first time I use this kind of noise with audio, so I just replicated what I normally do with graphics: let me figure out a couple sweet spots and it should start to behave ;)

**Comment by naus3a** [comment]
I think I could reproduce the issue: when noise speed became very low, noise position did not increase, causing a lock in the wave.

There might be a precision conversion issue between local variables and the value stored in the UI widgets: I'll investigate that. In the meantime I think I solved constraining the values on a slightly higher threshold.

**Comment by phdsg** [comment]
in my scenario i always had both knobs at "11" :)

**Comment by naus3a** [comment]
Good to know: I managed to make it happen by fiddling randomly :)
