### ISSUE TITLE
when speed knob is turned down the output value doesn't change

### ISSUE THREAD

**Issue by jeremywen** [naus3a/NauModular#4]
I was trying to get a real smooth slow lfo going but it doesn't seem to slow down enough.  It seems to just stop.  And then it gets worse over time.  It will stop at a higher and higher value.  Maybe related to that other issue https://github.com/naus3a/NauModular/issues/3

![perlin](https://user-images.githubusercontent.com/408586/33231548-d2f2736a-d1c4-11e7-810e-2fe24c4c9a3f.gif)

**Comment by naus3a** [comment]
The speed knob/input is the increment on the value used to generate Perlin noise. This value at the moment is just growing, so yes, both issues might be solved by a circular value range.

The flatline you're getting should not happen in any case: maybe there's some explicit casting needed too.
Will look into it.

**Comment by naus3a** [comment]
The lowest value for the speed knob was simply too low; I adjusted it to something that still shows up in the scope.
