### ISSUE TITLE
Fix versioning to be accepted into the Rack community repository

### ISSUE THREAD

**Issue by AndrewBelt** [naus3a/NauModular#7]
Rack v0.5.1 will include a plugin manager, and plugins need to follow the [versioning guidelines](https://github.com/VCVRack/Rack/issues/266) in order to be accepted. You can use this [example plugin Makefile](https://github.com/VCVRack/Tutorial/blob/master/Makefile) and [Tutorial.cpp file](https://github.com/VCVRack/Tutorial/blob/master/src/Tutorial.cpp) as a reference for making sure the version is the same in the C++, Makefile, and JSON manifest.

- Your plugin is versioned as `v1.0`. This needs to be `v0.5.something`.

Once you've fixed this, send a PR to the [Rack community repository](https://github.com/VCVRack/community) and remove the `"disabled"` property in the JSON manifest file.

**Comment by naus3a** [comment]
did it, thanks
