### ISSUE TITLE
compile error (linux)

### ISSUE THREAD

**Issue by derpology** [naus3a/NauModular#8]
With master at c7680cda91e7acd6f41301ea9bd79d950845d8a3 I get

```
src/Osc.cpp:209:26: error: ‘memset’ was not declared in this scope
     memset(_buf,0,_bufLen);
                          ^
src/Osc.cpp:210:49: error: ‘strlen’ was not declared in this scope
     uint32_t ii = (uint32_t)strlen(_addr.c_str());
                                                 ^
```

Including <string.h> appears to it fix for me, for example:

```
diff --git a/src/NauModular.hpp b/src/NauModular.hpp
index 6a20010..7691b83 100644
--- a/src/NauModular.hpp
+++ b/src/NauModular.hpp
@@ -20,6 +20,10 @@
 #include <mach/clock_types.h>
 #endif
 
+#if defined(TARGET_LINUX)
+#include <string.h>
+#endif
+
 using namespace rack;
 
 extern Plugin * plugin;
```

Not a linux cpp pro, so not sure how generically useful this info is - hope it's some use! :)

**Comment by naus3a** [comment]
Thanks: your fix looks like a a good generic one; I'm travelling but will include it in the source code as soon as I have a minute.
If you want to send a pull request, feel free.

The memset error is a weird one, by the way: the joy of multiplatform, right :)
